#!/bin/bash
sudo  ./out/server configurazioni/config1.txt &
pid=$!
sleep 2s
sudo  ./out/client -p -f /mysock -W TestSet/test1.txt,TestSet/test2.txt,TestSet/test3.txt,TestSet/test4.txt 
sudo  ./out/client -p -f /mysock -r TestSet/test1.txt,TestSet/test2.txt 
sudo valgrind --track-origins=yes ./out/client -p -f /mysock  -R n=3 -d download 

sleep 1s
kill -s SIGHUP $pid
wait $pid